import CAppBar from "@/components/site/CAppBar";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { CssBaseline } from "@mui/material";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Js Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <CssBaseline />
      <CAppBar />
      <main style={{ marginTop: "100px" }}>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt dolorum
          dolores provident adipisci voluptatem perferendis aut quis voluptatum
          voluptate assumenda sequi totam maxime accusamus voluptas non aliquam,
          odit fugit. Nihil fuga recusandae reprehenderit accusamus velit
          deserunt illo debitis nemo tempore facilis cumque quod officia culpa
          nobis reiciendis labore similique autem maxime magnam quam, tenetur,
          delectus voluptatibus. Est laborum saepe expedita ex eos hic nesciunt,
          magni, rerum quasi qui optio? Perspiciatis laborum accusantium
          excepturi, ea expedita nihil blanditiis fugiat vel porro dignissimos
          unde corporis placeat enim dolorem quam aliquid harum quia quibusdam
          necessitatibus. Minus quos sapiente similique laborum ullam, autem
          explicabo possimus totam placeat dolore? At repellat velit ipsum! Qui
          labore ipsa fugiat iste in, neque aliquam doloremque assumenda eos
          nemo cum perferendis officia ullam perspiciatis nisi error. Quae neque
          eveniet tempore minima eos libero, iusto molestiae ullam dolore, quos
          officia, commodi distinctio rem error repudiandae soluta ducimus ex
          inventore nisi enim. Odit commodi nobis aspernatur illum perspiciatis
          nostrum! Ex tempore similique placeat fugiat quidem quisquam culpa
          eaque quos, natus quasi dolore temporibus rem quo cumque libero
          tenetur, cum, nulla porro illo suscipit optio. Repellat, veniam. Natus
          quo doloribus velit inventore dicta. Obcaecati, officiis? Qui id
          facilis inventore explicabo sapiente molestias.
        </p>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt dolorum
          dolores provident adipisci voluptatem perferendis aut quis voluptatum
          voluptate assumenda sequi totam maxime accusamus voluptas non aliquam,
          odit fugit. Nihil fuga recusandae reprehenderit accusamus velit
          deserunt illo debitis nemo tempore facilis cumque quod officia culpa
          nobis reiciendis labore similique autem maxime magnam quam, tenetur,
          delectus voluptatibus. Est laborum saepe expedita ex eos hic nesciunt,
          magni, rerum quasi qui optio? Perspiciatis laborum accusantium
          excepturi, ea expedita nihil blanditiis fugiat vel porro dignissimos
          unde corporis placeat enim dolorem quam aliquid harum quia quibusdam
          necessitatibus. Minus quos sapiente similique laborum ullam, autem
          explicabo possimus totam placeat dolore? At repellat velit ipsum! Qui
          labore ipsa fugiat iste in, neque aliquam doloremque assumenda eos
          nemo cum perferendis officia ullam perspiciatis nisi error. Quae neque
          eveniet tempore minima eos libero, iusto molestiae ullam dolore, quos
          officia, commodi distinctio rem error repudiandae soluta ducimus ex
          inventore nisi enim. Odit commodi nobis aspernatur illum perspiciatis
          nostrum! Ex tempore similique placeat fugiat quidem quisquam culpa
          eaque quos, natus quasi dolore temporibus rem quo cumque libero
          tenetur, cum, nulla porro illo suscipit optio. Repellat, veniam. Natus
          quo doloribus velit inventore dicta. Obcaecati, officiis? Qui id
          facilis inventore explicabo sapiente molestias.
        </p>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt dolorum
          dolores provident adipisci voluptatem perferendis aut quis voluptatum
          voluptate assumenda sequi totam maxime accusamus voluptas non aliquam,
          odit fugit. Nihil fuga recusandae reprehenderit accusamus velit
          deserunt illo debitis nemo tempore facilis cumque quod officia culpa
          nobis reiciendis labore similique autem maxime magnam quam, tenetur,
          delectus voluptatibus. Est laborum saepe expedita ex eos hic nesciunt,
          magni, rerum quasi qui optio? Perspiciatis laborum accusantium
          excepturi, ea expedita nihil blanditiis fugiat vel porro dignissimos
          unde corporis placeat enim dolorem quam aliquid harum quia quibusdam
          necessitatibus. Minus quos sapiente similique laborum ullam, autem
          explicabo possimus totam placeat dolore? At repellat velit ipsum! Qui
          labore ipsa fugiat iste in, neque aliquam doloremque assumenda eos
          nemo cum perferendis officia ullam perspiciatis nisi error. Quae neque
          eveniet tempore minima eos libero, iusto molestiae ullam dolore, quos
          officia, commodi distinctio rem error repudiandae soluta ducimus ex
          inventore nisi enim. Odit commodi nobis aspernatur illum perspiciatis
          nostrum! Ex tempore similique placeat fugiat quidem quisquam culpa
          eaque quos, natus quasi dolore temporibus rem quo cumque libero
          tenetur, cum, nulla porro illo suscipit optio. Repellat, veniam. Natus
          quo doloribus velit inventore dicta. Obcaecati, officiis? Qui id
          facilis inventore explicabo sapiente molestias.
        </p>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt dolorum
          dolores provident adipisci voluptatem perferendis aut quis voluptatum
          voluptate assumenda sequi totam maxime accusamus voluptas non aliquam,
          odit fugit. Nihil fuga recusandae reprehenderit accusamus velit
          deserunt illo debitis nemo tempore facilis cumque quod officia culpa
          nobis reiciendis labore similique autem maxime magnam quam, tenetur,
          delectus voluptatibus. Est laborum saepe expedita ex eos hic nesciunt,
          magni, rerum quasi qui optio? Perspiciatis laborum accusantium
          excepturi, ea expedita nihil blanditiis fugiat vel porro dignissimos
          unde corporis placeat enim dolorem quam aliquid harum quia quibusdam
          necessitatibus. Minus quos sapiente similique laborum ullam, autem
          explicabo possimus totam placeat dolore? At repellat velit ipsum! Qui
          labore ipsa fugiat iste in, neque aliquam doloremque assumenda eos
          nemo cum perferendis officia ullam perspiciatis nisi error. Quae neque
          eveniet tempore minima eos libero, iusto molestiae ullam dolore, quos
          officia, commodi distinctio rem error repudiandae soluta ducimus ex
          inventore nisi enim. Odit commodi nobis aspernatur illum perspiciatis
          nostrum! Ex tempore similique placeat fugiat quidem quisquam culpa
          eaque quos, natus quasi dolore temporibus rem quo cumque libero
          tenetur, cum, nulla porro illo suscipit optio. Repellat, veniam. Natus
          quo doloribus velit inventore dicta. Obcaecati, officiis? Qui id
          facilis inventore explicabo sapiente molestias.
        </p>
      </main>
    </>
  );
}
