import { signIn } from "next-auth/react";
import Head from "next/head";
import Slider from "@mui/material/Slider";
import Box from "@mui/material/Box";
import CAppBar from "@/components/site/CAppBar";
import Hero from "@/components/site/CHero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CAppBar />
      </main>
    </>
  );
}
