import Head from "next/head";
import CAppBar from "@/components/site/CAppBar";

// import Slider from "@mui/material/Slider";
// import { styled } from "@mui/material/styles";

// const CustomSlider = styled(Slider)(({ theme }) => ({
//   color: "blueviolet",
//   "&:hover": {
//     color: "yellowgreen",
//   },
// }));

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CAppBar />
      </main>
    </>
  );
}
